bash2json v3.2.0

diff --git a/projects/bash2json b/projects/bash2json
--- a/projects/bash2json
+++ b/projects/bash2json
@@ -35,7 +35,7 @@ json_append() {
   local value="$3"
   local sub="$4"
       [[ "$input" == "" ]] && input='{}'
-  if [[ "$key" =~ \. ]]; then 
+  if [[ "${key:0:1}" != '{' && "${input:0:1}" != '[' && "$key" =~ \. ]]; then 
     IFS=' ' read append_key subkey <<< "${key/./ }"
     json_query "$input" "$append_key" false true
     local keyout="$json_query_output"
@@ -75,7 +75,7 @@ json_append() {
     json_append_output="${input/${keyout}/${newkeyout}}"
   else
     if [[ "${input:0:1}" == "{" ]]; then 
-      [ -z "$append_key" ] && error "key missing"
+      [ -z "$key" ] && error "key missing"
       [ -z "$value" ] && error "value missing"
       case "$value" in 
           true|false|[0-9]|null) : ;;
@@ -185,7 +185,6 @@ json_validate() {
     if ! "$isvalue" && [ ! -z "$value" ]; then 
       [[ "$value" =~ ^-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?$|^-?\.[0-9]+([eE][+-]?[0-9]+)?$ ]] || case "$value" in
         true|false|null) : ;;
-        $floatregex) : ;;
         *) [[ "${value:0:1}" == '"' && "${value: -1}" == '"' ]] || { error "invalid key value \`$value\`"; return 1; }  ;;
       esac 
       value=''
@@ -234,8 +233,7 @@ json_validate() {
     fi
   done <<< "$1"
   if (( dquotes % 2 )); then 
-    local missingq=$((dquotes-(dquotes-1))) 
-    ((missingq == 1 && depth > 0 )) && error 'expected `"` but got `EOF` instead' || error "missing $missingq \`\"\`"
+    (((dquotes-(dquotes-1)) == 1 && depth > 0 )) && error 'expected `"` but got `EOF` instead' || error "missing $missingq \`\"\`"
     code=1
   fi
   (( depth > 0 )) && error "missing ${depth} \`}\`" false && code=1
@@ -244,8 +242,6 @@ json_validate() {
   (( bdepth > 0 )) && error "missing ${bdepth} \`]\`" && code=1
   (( bdepth < 0 )) && error "missing ${bdepth//-} \`[\`" && code=1
   [ ! -z "${unquotedchars//\\n}" ] && error "unquoted characters: $unquotedchars" && code=1
-  #((code == 1)) && return 1
- # set -x
 }
 
 json_query() {
@@ -254,25 +250,24 @@ json_query() {
   json_query_output=""
   local sub="$4"
   local IFS=' ' 
-  local i=0
   for key in $query; do
     IFS='.' 
+    local i=0
     local input="$1"
-    ((++i))
     for subkey in $key; do
-      local sub=true
-      ((i == 1)) && [ ! -z "$json_query_output" ] && input="$json_query_output"
+      ((++i))
+      ((i > 1)) && [ ! -z "$json_query_output" ] && input="$json_query_output"
       if [[ "$subkey" =~ \[[0-9]*\] ]]; then 
         local index="${BASH_REMATCH[0]:1:-1}"
         if [[ "$index" == "" ]]; then 
           error "expected index number"
           return 1
         fi
-        if [[ "$subkey" == \[[0-9]*\] ]]; then
-          keyout="$input"
-        else
+        if [[ "$subkey" != \[[0-9]*\] ]]; then
+          subfunc=true
           $FUNCNAME "$input" "${subkey//\[[0-9]*\]}" false true
-          local keyout="$json_query_output"
+          local input="$json_query_output"
+          subfunc=false
         fi
         if [[ "${keyout:0:1}" != '[' ]]; then 
           error "cannot get index of non-array"
@@ -303,14 +298,6 @@ json_query() {
         done <<<"$input"
         mapfile -t arr <<< "$result"
         json_query_output="${arr[$index]}"
-        if [ ! -z "$json_query_output" ]; then
-          "${raw:=false}" && json_query_output="${json_query_output//\"}"
-        else 
-          json_query_output=null
-        fi
-        if ! "${sub:=false}"; then
-        "${raw:=false}" && printf "%b\n" "$json_query_output"  || printf "%s\n" "$json_query_output" 
-        fi
       else
         if [[ "$input"  =~ \"$subkey\":(.*) ]]; then
           string="${BASH_REMATCH[1]}"
@@ -333,9 +320,9 @@ json_query() {
               '"')
                 case "$char" in 
                   '\') escaped=true ;;
-                  '"') ((quoted ^= 1))  ;;
+                  '"') ((quoted ^= 1)) && newstring+='"'  ;;
                 esac
-                ((quoted == 0)) && newstring+="$char" && break
+                ((quoted == 0)) && break
               ;; 
               *) 
                 [[ "$char" == ',' ||  "$char" == '}' ]] && break 
@@ -433,7 +420,7 @@ json_to_arr() {
 function bash2json {
 local ultraverbose=false
 local orig_IFS="$IFS"
-local vers='v3.0.0'
+local vers='v3.2.0'
 local silent=false
 local validate=true
 data=''
@@ -468,14 +455,16 @@ esac
 done
 "$ultraverbose" && set -x
 if [[ "$action" != "help" && "$action" != "to_json" && "${allargs[0]:0:1}" != '{' && "${allargs[0]:0:1}" != '[' ]]; then
-if "${readfromstdin:=false}"; then 
-  local var="$(</dev/stdin)"
+if IFS= read -d '' -n 1  -t 0.001 || "${readfromstdin:=false}"; then 
+  local var 
+  read -rd '' var
   local query="${allargs[0]}"
   local arg2="${allargs[1]}"
   local arg3="${allargs[2]}"
 else 
   if [ -f "$input" ] || [ -L "$input" ]; then 
-    local var="$(<"$input")"
+    local var
+    read -rd '' var < "$input"
     local query="${allargs[0]}"
     local arg2="${allargs[1]}"
     local arg3="${allargs[2]}"
@@ -505,8 +494,8 @@ fi
 [[ "$action" != "help" ]] && [ -z "$var" ] && error "input missing"
 case "${action:=query}" in
 help)
+"${sourced:=false}" && echo "Usage: $FUNCNAME <input> <query|key?> <value?> [options?]" || echo "Usage: $0 <input> <query|key?> <value?> [options?]"
 cat <<-EOF
-Usage: $(! "$sourced" && echo "${0}" || echo "$FUNCNAME") <input> <query|key?> <value?> [options?]
 
 Available options:
 --from-json <input> <name?>         Convert JSON into associative/indexed array
@@ -529,9 +518,9 @@ Available options:
 
 --from-json generates single array command with all keys and subkeys
 Subkeys are returned as "declare -Ag <array name>=( ... [<key>.<subkey>]=<subkey value> )"
-
-$(! "$sourced" && echo "NOTE: --to-json requires bash2json to be sourced, otherwise bash2json wouldn't be able access arrays")
 EOF
+! "$sourced" && echo "NOTE: --to-json requires bash2json to be sourced, otherwise bash2json wouldn't be able access arrays"
+
 ;;
 validate)  json_validate "$var" ;;
 append)    json_append "$var" "$query" "$arg2" ;;
